name: Build and Deploy Nightly

on:
  push:
    branches:
      - nightly

permissions:
  contents: write
 
jobs:
  nightly:
    name: Build Nightly
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # disabled temporaly due to a problem os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . nuitka zstandard
          
      - name: Build with Nuitka
        run: |
          hatch run python -m nuitka --standalone --assume-yes-for-download --output-dir=dist src/main.py

      #- name: Package Windows build
      #  if: matrix.os == 'windows-latest'
      #  shell: pwsh
      #  run: |
      #    Compress-Archive -Path dist/main.dist/* -DestinationPath LCE-Qt-Launcher-Windows.zip

      - name: Package Linux build
        if: matrix.os == 'ubuntu-latest'
        run: |
          tar -czf LCE-Qt-Launcher-Linux.tar.gz -C dist/main.dist .

      - name: Upload Nightly
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: Nightly Release
          body: "
            > [!NOTE]\n
            > There is no MacOS pre-compiled build since, I do not have a mac\n
            > to the software, so a compilation from source is needed to test\n
            > on MacOS\n
            \n
            >[!INFORMATION]
            > Automatic Linux Build diabled due to a issue, will be re-enabled when fixes  
          
            Experimental Build (Nightly) generated by GitHub Action.
            The nighy build are experimental nuitka compilation
            from the nighly version for the more stable build,
            these are available via manual compilation on the master branch
            Pre-compiled stable binary will be release when the first alpha release"
          files: |
            *.zip
            *.tar.gz
