name: Build and Deploy Nightly

on:
  push:
    branches:
      - master

permissions:
     contents: write

jobs:
  nightly:
    name: Build Nightly
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka

      - name: Build with Nuitka for Linux
        if: matrix.os == 'ubuntu-latest' 
        run: |
          python -m nuitka --onefile --standalone --enable-plugin=pyside6 --output-dir=dist src/launcher.py

      - name: Build with Nuitka for Windows
        if: matrix.os == 'ubuntu-latest' 
        run: |
          python -m nuitka --enable-plugin=pyside6 --output-dir=dist src/launcher.py

      - name: Package Windows build
        if: matrix.os == 'windows-latest'
        run: |
          7z a -r LCE-WQt-Launcher-Windows.zip dist/* 

      - name: Package Linux build
        if: matrix.os == 'ubuntu-latest'
        run: |
          tar -czf LCE-WQt-Launcher-Linux.tar.gz dist/*

      - name: Upload Nightly
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: Nightly Release
          body: |
            Experimental nightly builds for Windows and Linux.
          files: |
            *.zip
            *.tar.gz