name: Build and Publish Stable Version

on:
  push:
    tag: ["v0.0.1b"]

jobs:
  build_windows_installer:
    name: Build the Inno Setup Installer
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: packages/windows/windows-setup.iss
          options: '/O+ /F"LCE_Qt_Launcher_Windows_Setup"'
  build_arch_installer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate package
        uses: heyhusen/archlinux-package-action@v3.0.0
        with:
          flags: '-p packages/linux/stable/PKGBUILD'
          namcap: true
          srcinfo: true